### ISSUE TITLE
Could this be useful?

### ISSUE THREAD

**Issue by RaydenX93** [FoxdieTeam/mgs_reversing#143]
My knowledge of reversing PSX games is none, but could this be useful for this wonderful project?

https://github.com/OpenDriver2/REDRIVER2
Namely: https://github.com/OpenDriver2/REDRIVER2/tree/master/src_rebuild/PsyX

Keep it up! 👍

**Comment by paulsapps** [comment]
Once this project is finished that would be useful for producing a test windows build
