### ISSUE TITLE
FEATURE REQUEST - Add Missing Stuff from the Original Western Release of MGS

### ISSUE THREAD

**Issue by filipe-maia** [FoxdieTeam/mgs_reversing#1989]
Hi.

I have a request: add the option to Metal Gear Solid Integral to have the missing features from Metal Gear Solid (the Policenauts jingle, naked Johnny (I find that blurred is funnier than not blurred), ...).

There is an unreleased complete English translation for MGS Integral for PS1 here, don't know if you need it: https://youtu.be/lNAseZGI12M

Thanks.

**Comment by Jayveer** [comment]
That isn't really the objective of this project, we are decompiling the game to match exactly with what's in the integral version. However it should be easy enough for someone to use the project's base to swap out parts of the game such as this when the decomplication is done.
